SELECT SUM(`ManufacturedQty`) AS TOTAL_MANUFACTURED_QTY FROM Prod_Data;
SELECT CONCAT(ROUND(SUM(`ManufacturedQty`)/1000000, 2), " M") AS TOTAL_MANUFACTURED_QTY FROM Prod_Data;

-- TOTAL RejectedQty
SELECT SUM(`RejectedQty`) AS TOTAL_REJECTED_QTY FROM Prod_Data;
SELECT CONCAT(ROUND(SUM(`RejectedQty`)/1000, 2), " K") AS TOTAL_REJECTED_QTY FROM Prod_Data;

-- TOTAL ProducedQty
SELECT SUM(`ProducedQty`) AS TOTAL_PRODUCED_QTY FROM Prod_Data;
SELECT CONCAT(ROUND(SUM(`ProducedQty`)/1000000, 2), " M") AS TOTAL_PRODUCED_QTY FROM Prod_Data;

-- TOTAL ProcessedQty
SELECT SUM(`ProcessedQty`) AS TOTAL_PROCESSED_QTY FROM Prod_Data;
SELECT CONCAT(ROUND(SUM(`ProcessedQty`)/1000000, 2), " M") AS TOTAL_PROCESSED_QTY FROM Prod_Data;

-- WASTAGE RATE
SELECT CONCAT(ROUND((SUM(`RejectedQty`)/ SUM(`ManufacturedQty`)) * 100, 2), " %") AS WASTAGE_RATE FROM Prod_Data;

-- TOTAL EMPLOYEES
SELECT COUNT(DISTINCT `EmpCode`) AS TOTAL_EMPLOYEES FROM Prod_Data;

-- TOTAL MACHINES
SELECT COUNT(DISTINCT `MachineCode`) AS TOTAL_MACHINES FROM Prod_Data;

-- DEPARTMENT WISE MANUFACTURED VS REJECTED
SELECT `DEPARTMENTNAME`, 
CONCAT(ROUND(SUM(`ManufacturedQty`)/1000000, 2), " M") AS MANUFACTURED_QTY,
CONCAT(ROUND(SUM(`RejectedQty`)/1000, 2), " K") AS REJECTED_QTY
FROM Prod_Data 
GROUP BY `DEPARTMENTNAME`;

-- EMPLOYEE WISE RejectedQty
SELECT `EMPNAME`, SUM(`RejectedQty`) AS REJECTED_QTY
FROM Prod_Data
GROUP BY `EMPNAME`
HAVING SUM(`RejectedQty`) > 0
ORDER BY SUM(`RejectedQty`) DESC;
# LIMIT 10;

-- MACHINE WISE RejectedQty
SELECT `MACHINENAME`, SUM(`RejectedQty`) AS REJECTED_QTY
FROM Prod_Data 
GROUP BY `MACHINENAME`
HAVING SUM(`RejectedQty`) > 0
ORDER BY SUM(`RejectedQty`) DESC;
# LIMIT 10;

-- ManufacturedQty VS RejectedQty
SELECT `FISCALDATE`, 
SUM(`ManufacturedQty`) AS MANUFACTURED_QTY, 
SUM(`RejectedQty`) AS REJECTED_QTY
FROM Prod_Data 
GROUP BY `FISCALDATE`
ORDER BY `FISCALDATE`;

-- PRODUCTION COMPARISION TREND
SELECT `FISCALDATE`,
SUM(`ManufacturedQty`) AS MANUFACTURED_QTY,
SUM(`ProducedQty`) AS PRODUCED_QTY,
SUM(`ProcessedQty`) AS PROCESSED_QTY,
SUM(`RejectedQty`) AS REJECTED_QTY
FROM Prod_Data
GROUP BY `FISCALDATE`
ORDER BY `FISCALDATE`;